[project]
name = "model-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.10.1",
    "cog>=0.16.7",
    "dotenv>=0.9.9",
    "fastapi>=0.115.14",
    "hf-xet>=1.1.10",
    "huggingface-hub>=0.35.1",
    "torch>=2.8.0",
    "transformers>=4.56.2",
    "uvicorn>=0.37.0",
]
